const routes=[...document.querySelectorAll('[data-route-page]')];
const indexScreen=document.getElementById('indexScreen');
const indexButtons=[...document.querySelectorAll('#indexList [data-route]')];
const curtain=document.querySelector('.page-curtain');
const cursor=document.querySelector('.cursor');
const sourceDrawer=document.getElementById('sourceDrawer');
const sourceBody=document.getElementById('sourceBody');
let current='home';

const sources={
 ifpi:{title:'IFPI · Global Music Report 2026',publisher:'IFPI',date:'18 Mar 2026',scope:'Calendar year 2025 / global recorded music revenues',definition:'Revenue data supplied by record companies and IFPI national groups. Free State of the Industry figures used.',url:'https://www.ifpi.org/global-music-report-2026-global-recorded-music-revenues-grow-6-4-as-record-companies-drive-innovation/',note:'Used for $31.7B global revenue, +6.4% growth, 69.6% streaming share, Asia +10.9%, Asia 45.1% of global physical revenue, Japan +8.9%, China +20.1%, South Korea #7.'},
 kpop:{title:'Luminate · Beyond K-Pop: Preserving South Korea’s Musical Future',publisher:'Luminate',date:'26 May 2026',scope:'2025 streaming / Luminate genre classification',definition:'K-pop foreign streams exclude Republic of Korea. Article states nearly three of every four global K-pop streams came from foreign listeners.',url:'https://luminatedata.com/blog/beyond-k-pop-preserving-south-koreas-musical-future/',note:'Used for ≈75% overseas share, 48 artists = 39% / ~50B foreign K-pop streams, and R&B/Hip-Hop comparator (112 artists = 36%).'},
 superfan:{title:'Luminate · 2026 Midyear Report',publisher:'Luminate',date:'15 Jul 2026',scope:'U.S. music listeners / H1 2026',definition:'Superfan = listener engaging with artists/music in five or more ways. CD sales cover U.S. H1 2026.',url:'https://luminatedata.com/blog/luminate-2026-midyear-report-trends-in-music-television-film/',note:'Used for 20% U.S. superfans and 16.3M U.S. CD sales in H1 2026 (+16.0% YoY).'},
 physical:{title:'Luminate · Taylor Swift Wasn’t the Only Winner of Physical Sales in 2025',publisher:'Luminate',date:'31 Mar 2026',scope:'U.S. 2025 physical/CD sales + U.S. Music 360 survey',definition:'Survey result: 27% of U.S. K-pop fans bought a CD in 2025 vs 19% of general U.S. music listeners.',url:'https://luminatedata.com/blog/taylor-swift-wasnt-the-only-winner-of-physical-sales-in-2025/',note:'Used for 27% vs 19%, seven of U.S. top 10 CD albums being K-pop groups, and repeat-purchase context.'},
 spotify:{title:'Spotify · Loud & Clear 2026',publisher:'Spotify',date:'11 Mar 2026',scope:'Spotify 2025 royalties',definition:'Company-reported royalties generated through Spotify; payout is to rights holders/music industry, not artist take-home income.',url:'https://newsroom.spotify.com/2026-03-11/loud-and-clear-music-economics-highlights/',note:'Used for $11B+ 2025 payout, 13,800+ artists generating $100K+, and 1,500+ generating $1M+.'},
 youtube:{title:'YouTube · $8 Billion Music Payout',publisher:'YouTube',date:'23 Oct 2025',scope:'12 months Jul 2024–Jun 2025',definition:'Company-reported payout to music industry from ads and subscriptions.',url:'https://blog.youtube/news-and-events/8-billion-youtubes-twin-engine-continues-to-fuel-the-future-of-music/',note:'Used for $8B+ payout, 125M+ Music/Premium subscribers incl. trials, and 2B+ logged-in monthly music-video viewers.'},
 tws:{title:'TWS · NO TRAGEDY Official Photo: FINAL MOVE Ver.',publisher:'Weverse / TWS',date:'Apr 2026',scope:'Official artist image',definition:'Official promotional image published on TWS Weverse media.',url:'https://weverse.io/tws/media/4-225830840',note:'Used only as visual reference. Artist-case interpretation is a self-initiated desk-research sample and does not claim access to HYBE/PLEDIS internal data.'}
};
function openIndex(){indexScreen.classList.add('open');indexScreen.setAttribute('aria-hidden','false');syncIndex()}
function closeIndex(){indexScreen.classList.remove('open');indexScreen.setAttribute('aria-hidden','true')}
document.querySelectorAll('.js-open-index').forEach(b=>b.addEventListener('click',openIndex));
document.querySelectorAll('.js-close-index').forEach(b=>b.addEventListener('click',closeIndex));
function syncIndex(){indexButtons.forEach(b=>b.classList.toggle('active',b.dataset.route===current))}
function runReveal(page){const els=[...page.querySelectorAll('.reveal-up')];els.forEach(e=>e.classList.remove('in'));requestAnimationFrame(()=>els.forEach((e,i)=>setTimeout(()=>e.classList.add('in'),100+i*95)))}
function go(route){if(route===current){closeIndex();return}curtain.classList.remove('run');void curtain.offsetWidth;curtain.classList.add('run');setTimeout(()=>{routes.forEach(r=>r.classList.toggle('active',r.dataset.routePage===route));current=route;location.hash=route==='home'?'':route;syncIndex();closeIndex();const active=routes.find(r=>r.dataset.routePage===route);const scroll=active.querySelector('.chapter-scroll');if(scroll)scroll.scrollTop=0;runReveal(active)},370)}
indexButtons.forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));
document.querySelectorAll('[data-prev],[data-next]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.prev||b.dataset.next)));
function openSource(key){const s=sources[key];if(!s)return;sourceBody.innerHTML=`<div class="source-block"><h3>${s.title}</h3><p>${s.note}</p><dl><div><dt>PUBLISHER</dt><dd>${s.publisher}</dd></div><div><dt>PUBLISHED</dt><dd>${s.date}</dd></div><div><dt>SCOPE</dt><dd>${s.scope}</dd></div><div><dt>DEFINITION</dt><dd>${s.definition}</dd></div></dl><a href="${s.url}" target="_blank" rel="noreferrer">OPEN ORIGINAL SOURCE ↗</a></div>`;sourceDrawer.classList.add('open');sourceDrawer.setAttribute('aria-hidden','false')}
function closeSource(){sourceDrawer.classList.remove('open');sourceDrawer.setAttribute('aria-hidden','true')}
document.querySelectorAll('[data-source]').forEach(b=>b.addEventListener('click',()=>openSource(b.dataset.source)));
document.querySelectorAll('[data-source-close]').forEach(b=>b.addEventListener('click',closeSource));
if(matchMedia('(pointer:fine)').matches){let x=innerWidth/2,y=innerHeight/2,tx=x,ty=y;addEventListener('mousemove',e=>{tx=e.clientX;ty=e.clientY});function loop(){x+=(tx-x)*.18;y+=(ty-y)*.18;cursor.style.left=x+'px';cursor.style.top=y+'px';requestAnimationFrame(loop)}loop();document.querySelectorAll('button,a').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('link'));el.addEventListener('mouseleave',()=>cursor.classList.remove('link'))})}
document.querySelectorAll('.donut').forEach(d=>d.style.setProperty('--p',d.dataset.value||39));
addEventListener('keydown',e=>{if(e.key==='Escape'){closeIndex();closeSource();return}const order=['home','market','kpop','fandom','dsp','tws','method'];const i=order.indexOf(current);if(['ArrowRight','PageDown'].includes(e.key))go(order[Math.min(i+1,order.length-1)]);if(['ArrowLeft','PageUp'].includes(e.key))go(order[Math.max(i-1,0)]) });
const initial=location.hash.replace('#','');if(initial&&routes.some(r=>r.dataset.routePage===initial)){current=initial;routes.forEach(r=>r.classList.toggle('active',r.dataset.routePage===initial))}syncIndex();runReveal(routes.find(r=>r.classList.contains('active')));