const chapters=[['00','executive','Executive Brief','Key market signals'],['01','market','Market Structure','Revenue / format / region'],['02','kpop','K-pop Export','Overseas consumption / concentration'],['03','fandom','Fandom Economics','Engagement / physical / conversion'],['04','dsp','DSP & Discovery','Platform / discovery / payout'],['05','artist','Artist Case · TWS','Release architecture / KPI'],['06','watch','Strategic Watchlist','2H 2026 signals'],['07','work','Selected Work','Applied portfolio'],['08','method','Research Method','Source / definition / note']];
const indexList=document.getElementById('indexList'),drawerList=document.getElementById('drawerList');
chapters.forEach((c,i)=>{const a=document.createElement('a');a.className='index-item';a.style.setProperty('--i',i);a.href='#'+c[1];a.dataset.target=c[1];a.innerHTML=`<span class="n">${c[0]}</span><strong>${c[2]}</strong><small>${c[3]}</small>`;indexList.appendChild(a);const d=document.createElement('a');d.href='#'+c[1];d.dataset.target=c[1];d.innerHTML=`<span class="dn">${c[0]}</span><strong>${c[2]}</strong>`;drawerList.appendChild(d)});
const overlay=document.getElementById('indexOverlay'),drawer=document.getElementById('chapterDrawer'),wipe=document.querySelector('.wipe');
function openIndex(){overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');document.body.classList.add('lock')}
function closeIndex(){overlay.classList.remove('open');overlay.setAttribute('aria-hidden','true');document.body.classList.remove('lock')}
document.querySelectorAll('.js-open-index').forEach(b=>b.addEventListener('click',openIndex));document.querySelectorAll('.js-close-index').forEach(b=>b.addEventListener('click',closeIndex));
document.querySelectorAll('.js-open-drawer').forEach(b=>b.addEventListener('click',()=>drawer.classList.toggle('open')));document.getElementById('drawerClose').addEventListener('click',()=>drawer.classList.remove('open'));
function navigateTo(id){const el=document.getElementById(id);if(!el)return;wipe.classList.remove('run');void wipe.offsetWidth;wipe.classList.add('run');setTimeout(()=>{closeIndex();drawer.classList.remove('open');el.scrollIntoView({behavior:'instant',block:'start'})},370);setTimeout(()=>wipe.classList.remove('run'),900)}
document.querySelectorAll('[data-target]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();navigateTo(a.dataset.target)}));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeIndex();drawer.classList.remove('open')}});
const sectionEls=chapters.map(c=>document.getElementById(c[1])).filter(Boolean),currentLabel=document.getElementById('currentLabel');let current='executive';
function setActive(id){current=id;const c=chapters.find(x=>x[1]===id);if(c)currentLabel.textContent=`${c[0]} · ${c[2]}`;document.querySelectorAll('.index-item,.drawer-list a').forEach(a=>a.classList.toggle('active',a.dataset.target===id))}
const ioActive=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-34% 0px -55% 0px'});sectionEls.forEach(s=>ioActive.observe(s));
const header=document.querySelector('.header'),progress=document.querySelector('.progress i');window.addEventListener('scroll',()=>{const y=scrollY,d=document.documentElement.scrollHeight-innerHeight;progress.style.width=(d?y/d*100:0)+'%';header.classList.toggle('scrolled',y>25)},{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');e.target.querySelectorAll('.year-bar').forEach(b=>b.querySelector('i').style.height=b.dataset.h+'%');e.target.querySelectorAll('.track i').forEach(i=>i.style.width=i.dataset.w+'%');e.target.querySelectorAll('[data-count]').forEach(countUp);io.unobserve(e.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
function countUp(el){if(el.dataset.done)return;el.dataset.done=1;const end=+el.dataset.count,d=end%1?1:0,p=el.dataset.prefix||'',s=el.dataset.suffix||'';let st=performance.now();function tick(t){let k=Math.min(1,(t-st)/900),v=end*(1-Math.pow(1-k,3));el.textContent=p+v.toFixed(d)+s;if(k<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
const cur=document.querySelector('.cursor'),dot=document.querySelector('.cursor-dot');if(matchMedia('(pointer:fine)').matches){let x=0,y=0,cx=0,cy=0;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;dot.style.transform=`translate(${x}px,${y}px)`},{passive:true});function follow(){cx+=(x-cx)*.16;cy+=(y-cy)*.16;cur.style.transform=`translate(${cx}px,${cy}px)`;requestAnimationFrame(follow)}follow();document.querySelectorAll('a,button,.artist-hero').forEach(el=>{el.addEventListener('mouseenter',()=>cur.classList.add('is-link'));el.addEventListener('mouseleave',()=>cur.classList.remove('is-link'))})}
addEventListener('keydown',e=>{if(overlay.classList.contains('open')||drawer.classList.contains('open'))return;let i=chapters.findIndex(c=>c[1]===current);if(e.key==='PageDown'||(e.altKey&&e.key==='ArrowDown')){e.preventDefault();navigateTo(chapters[Math.min(chapters.length-1,i+1)][1])}if(e.key==='PageUp'||(e.altKey&&e.key==='ArrowUp')){e.preventDefault();navigateTo(chapters[Math.max(0,i-1)][1])}});setActive('executive');